### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when uploading full image

### ISSUE THREAD

**Issue by xulman** [fiji-hpc/hpc-datastore-fiji#26]
writing full 2D(!) image (with the Fiji plugin) into a dataset that's been created "Create new dataset from the current image" resulted in the following report:

```
versions = []
[INFO] CREATED JSON:
{"uuid":null,"voxelType":"uint8","dimensions":[5750,10750,1],"timepoints":1,"channels":2,"angles":1,"voxelUnit":"px","voxelResolution":[1.0,1.0,1.0],"timepointResolution":{"value":90.0,"unit":"seconds"},"channelResolution":{"value":0.0,"unit":"channel"},"angleResolution":{"value":0.0,"unit":"NA"},"compression":"gzip","resolutionLevels":[{"resolutions":[1,1,1],"blockDimensions":[96,96,96],"dimensions":[5750,10750,1]},{"resolutions":[3,3,3],"blockDimensions":[96,96,96],"dimensions":[1916,3583,1]}],"versions":[],"label":"dw__damagedRoad1_ortoFoto__REMOVE","transformations":null,"viewRegistrations":null,"timepointIds":null,"datasetType":null}
[INFO] Created dataset UUID: 25a2640a-f210-4867-87cb-6a717e4df6d2
[INFO] Polling URL: http://localhost:9080/bdv/25a2640a-f210-4867-87cb-6a717e4df6d2
dataset:25a2640a-f210-4867-87cb-6a717e4df6d2, version:0
[ERROR] Command errored: Write full image
java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.view.SubsampleView$SubsampleRandomAccess.setPosition(SubsampleView.java:206)
	at net.imglib2.view.RandomAccessibleIntervalCursor.reset(RandomAccessibleIntervalCursor.java:137)
	at net.imglib2.view.RandomAccessibleIntervalCursor.<init>(RandomAccessibleIntervalCursor.java:79)
	at net.imglib2.view.IterableRandomAccessibleInterval.cursor(IterableRandomAccessibleInterval.java:89)
	at net.imglib2.view.IntervalView.cursor(IntervalView.java:168)
	at cz.it4i.fiji.legacy.util.Imglib2Types$TypeHandler.imgIntervalIntoBlock(Imglib2Types.java:66)
	at cz.it4i.fiji.legacy.common.ImagePlusTransferrer.writeWithAType(ImagePlusTransferrer.java:390)
	at cz.it4i.fiji.legacy.WriteFullImage$LocalWriter.writeNow(WriteFullImage.java:287)
	at cz.it4i.fiji.legacy.WriteFullImage.run(WriteFullImage.java:86)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xulman** [comment]
the code was trying to subsample always in three dimensions, even when the image was 2D
fixed in commit b294207a845f72bd5424d96054f4e89aeccc7cfa
